<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GeneralSettings extends Model
{
    protected $table    = 'generalsettings';
    protected $fillable = [
        'logo',
        'footer_logo',
        'favicon',
        'lazy_baner',
        'og_images',
        'loader',
        'admin_loader',
        'title',
        'theme_color',
        'footer_color',
        'time_zone',
        'copyright_text',
        'copyright_color',
        'footer_text',
        'notice',
        'sompadok',
        'nirbahi_sompadok',
        'barta_sompadok',
        'live_tv',
        'facebookpage_id',
        'address',
        'email_address',
        'google_map',


        'dhaka',
        'khulna',
        'rajshahi',
        'ctg',
        'maymonsingh',
        'barishal',
        'rangpur',
        'syleth',
        'fazar',
        'jahar',
        'achar',
        'magrib',
        'esha',
        'jumma',
        'sidebar_ads',
        'header_top_ads',
        'section_one_point_one_ads',
        'section_one_point_two_ads',
        'section_two_point_one_ads',
        'section_two_point_two_ads',
        'section_three_point_one_ads',
        'section_three_point_two_ads',
        'section_four_point_one_ads',
        'section_four_point_two_ads',
        'section_four_point_three_ads',
        'section_five_point_one_ads',
        'section_five_point_two_ads',
        'section_six_point_one_ads',
        'section_six_point_two_ads',
        'section_six_point_three_ads',
        'section_seven_point_one_ads',
        'section_seven_point_two_ads',
        'section_seven_point_three_ads',
        'section_eight_point_one_ads',
        'section_eight_point_two_ads',
        'section_nine_point_one_ads',
        'section_nine_point_two_ads',
        'section_ten_point_one_ads',
        'section_ten_point_two_ads',
        'adsense_code',
        'search_console',

        'mobile',
        'tags',
        'error_photo',
        'error_title',
        'error_text',
        'driver',
        'smtp_host',
        'smtp_port',
        'email_encryption',
        'smtp_user',
        'smtp_pass',
        'from_email',
        'from_name',
        'is_smtp',
        'is_verification_email',
        'hot_news'
    ];
    public $timestamps  = false;
}
